### PR TITLE
[Feature]: Run project on Docker in Dev mode

### LINKED ISSUE #150: [FEATURE]: Run dev environment on Docker
## Summary

Create like `docker-compose.dev.yml` where is created containers to run **frontend** and **backend**, like how you do on terminal, but that way you don't need have two terminals opened to run the project.

### PR DESCRIPTION
**Pull request by dsousa12**
Relates to #150 

## Screenshots (if visual changes)
It's not a visual change, but I leave some screenshots related with this change:
image

### Hot reloading
- On Frontend:
image

- On Backend:
image

## Proposed Changes

  - Create separated files to run docker as **production mode** and **development mode** <small>(localhost mode)</small>
     - **Why?** this way you don't need open 2 terminals to run a frontend and the backend manually, you can create the containers, and start or stop both or only one.
  
@xgeekshq/d-c-infra can review please?

This pull request is intended to close #150

### CODE REVIEW

**Comment by dsousa12** [comment]
**Note:** it's necessary update the **README**

# How to run:
- `docker-compose --file docker-compose.dev.yaml up -d`: use this command to use the `docker-compose.dev` file, where I use specific `Docker` files, instead running on production mode

**Review by nunocaseiro — COMMENTED** [review]
Before the push we need to modify the github actions in order to use the new version. However I see that you aren't using the `package-lock.json` and `npm ci` or `yarn install --frozen-lockfile`to install the dependencies. That's why the context was the root folder. By doing that we guarantee the same package versions and avoid some errors that can appear in newer versions by using the same `package-lock` that it is correctly running in our local machine

**Comment by dsousa12** [comment]
> **Note:** it's necessary update the **README**
> # How to run:
> 
>     * `docker-compose --file docker-compose.dev.yaml up -d`: use this command to use the `docker-compose.dev.yaml` file.
>       
>       * This file use a different `Dockerfiles` (not the production mode files)

Working on this section in [Wiki](https://github.com/xgeekshq/divide-and-conquer/wiki)

**Comment by dsousa12** [comment]
> Before the merge we need to modify the github actions in order to use the prod versions of the docker files. Now we have an extra folder `docker` in each app. I believe we just need to update the docker build command on each github action workflow. Great job!

@nunocaseiro already done this change, can you see if everything it's ok?

**Comment by nunocaseiro** [comment]
@all-contributors please add @dsousa12 as contributor for code and docs

**Review by nunocaseiro — APPROVED** [review]
LGTM 🚀  
Amazing job!

**Pull request merged**
